### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by IgorGanapolsky** [pfn/protify#11]
Hi,
when I run `sbt` after doing all the steps in your README, I get the stacktrace as in screenshot:
<img width="973" alt="screen shot 2015-12-04 at 12 21 07 am" src="https://cloud.githubusercontent.com/assets/201209/11582468/3b3e5092-9a1d-11e5-9069-127f8ac04fa4.png">

Please advise,
Igor

**Comment by pfn** [comment]
You didn't add android-gradle-build into project/plugins.sbt

##

**Comment by IgorGanapolsky** [comment]
Thanks for the nice repo.  @pfn @changetip $1.

**Comment by changetip** [comment]
Hi @pfn, @IgorGanapolsky sent you a tip worth 2,775 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/925337)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
