### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by IgorGanapolsky** [pfn/protify#12]
Hello, 
I am trying to run a project in Android Studio.  I followed your README.  When I run `~protify` command, here is the stacktrace I get:

> com.android.ide.common.process.ProcessException: Return code 1 for process '/Users/eazyigz/Library/Android/sdk/build-tools/23.0.2/aapt package -f --no-crunch -I /Users/eazyigz/Library/Android/sdk/platforms/android-23/android.jar -M /Users/eazyigz/git/square/u2020/target/android/intermediates/manifest/AndroidManifest.xml -S /Users/eazyigz/git/square/u2020/target/android/intermediates/res -A /Users/eazyigz/git/square/u2020/target/android/intermediates/assets -m -J /Users/eazyigz/git/square/u2020/target/android/generated/source -F /Users/eazyigz/git/square/u2020/target/android/intermediates/packaging/resources-debug.ap_ -G /Users/eazyigz/git/square/u2020/target/android/intermediates/proguard/proguard.txt --debug-mode --custom-package com.jakewharton.u2020 -0 apk --output-text-symbols /Users/eazyigz/git/square/u2020/target/android/generated/source'
>         at com.android.ide.common.process.ProcessResultImpl.assertNormalExitValue(ProcessResultImpl.java:45)
>         at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:919)
>         at android.Resources$.aapt(resources.scala:242)
>         at android.Tasks$$anonfun$48$$anonfun$apply$54.apply(tasks.scala:609)
>         at android.Tasks$$anonfun$48$$anonfun$apply$54.apply(tasks.scala:604)
>         at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:903)
>         at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:901)
>         at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:186)
>         at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:186)
>         at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:200)
>         at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:196)
>         at sbt.Difference.apply(Tracked.scala:175)
>         at sbt.Difference.apply(Tracked.scala:157)
>         at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:196)
>         at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:195)
>         at sbt.Difference.apply(Tracked.scala:175)
>         at sbt.Difference.apply(Tracked.scala:151)
>         at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:195)
>         at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:193)
>         at android.Tasks$.withCachedRes(tasks.scala:904)
>         at android.Tasks$$anonfun$48.apply(tasks.scala:604)
>         at android.Tasks$$anonfun$48.apply(tasks.scala:599)
>         at scala.Function11$$anonfun$tupled$1.apply(Function11.scala:35)
>         at scala.Function11$$anonfun$tupled$1.apply(Function11.scala:34)
>         at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
>         at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
>         at sbt.std.Transform$$anon$4.work(System.scala:63)
>         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
>         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
>         at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
>         at sbt.Execute.work(Execute.scala:235)
>         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
>         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
>         at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
>         at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> [error](android:packageResources) com.android.ide.common.process.ProcessException: Return code 1 for process '/Users/eazyigz/Library/Android/sdk/build-tools/23.0.2/aapt package -f --no-crunch -I /Users/eazyigz/Library/Android/sdk/platforms/android-23/android.jar -M /Users/eazyigz/git/square/u2020/target/android/intermediates/manifest/AndroidManifest.xml -S /Users/eazyigz/git/square/u2020/target/android/intermediates/res -A /Users/eazyigz/git/square/u2020/target/android/intermediates/assets -m -J /Users/eazyigz/git/square/u2020/target/android/generated/source -F /Users/eazyigz/git/square/u2020/target/android/intermediates/packaging/resources-debug.ap_ -G /Users/eazyigz/git/square/u2020/target/android/intermediates/proguard/proguard.txt --debug-mode --custom-package com.jakewharton.u2020 -0 apk --output-text-symbols /Users/eazyigz/git/square/u2020/target/android/generated/source'

Any ideas?
Thanks,
Igor

**Comment by pfn** [comment]
Always provide full logs

**Comment by IgorGanapolsky** [comment]
That is the full log from Logcat in Android Studio.

**Comment by pfn** [comment]
That is not the full output of the build command.

##

**Comment by IgorGanapolsky** [comment]
That is what Logcat shows me.

**Comment by pfn** [comment]
That is not logcat

##

**Comment by IgorGanapolsky** [comment]
Then what is it?

**Comment by pfn** [comment]
A partial log of build output

##

**Comment by IgorGanapolsky** [comment]
Here is the screenshot of logcat:
<img width="1440" alt="screen shot 2015-12-06 at 11 27 00 pm" src="https://cloud.githubusercontent.com/assets/201209/11619060/1c4e05a0-9c71-11e5-839a-3f559d3eda26.png">

**Comment by pfn** [comment]
Go to the command line, run `sbt protify` paste the full output

**Comment by IgorGanapolsky** [comment]
Here, terminal command line inside of Android Studio.  Running `sbt protify` screenshot:
<img width="1440" alt="screen shot 2015-12-06 at 11 30 24 pm" src="https://cloud.githubusercontent.com/assets/201209/11619074/649ad054-9c71-11e5-93eb-46e9faaad6a5.png">

**Comment by IgorGanapolsky** [comment]
continuation from screenshot:
<img width="1440" alt="screen shot 2015-12-06 at 11 30 26 pm" src="https://cloud.githubusercontent.com/assets/201209/11619075/6b8d7a1a-9c71-11e5-8d87-192f8963a182.png">

**Comment by pfn** [comment]
That's not logcat, that's a screenshot of the terminal tool window. And the
messages are clear, you are missing appcompat.

##

**Comment by IgorGanapolsky** [comment]
A) You told me to run terminal command.  That's what i did.
B) The project builds AND runs fine with gradle.  What is causing it to
fail in SBT?

**Comment by pfn** [comment]
You tell me, I have u2020 building fine as demonstrated in a test case. At:

https://github.com/pfn/android-sdk-plugin/blob/master/sbt-test/gradle-build/u2020/

##

**Comment by IgorGanapolsky** [comment]
I just ran `sbt protify` on your test case in my Android Studio.  Got this build error:

> sbt.ResolveException: unresolved dependency: com.hanhuy.sbt#android-gradle-build;1.1.9-SNAPSHOT: not found
>         at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
>         at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
>         at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
>         at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
>         at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
>         at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
>         at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
>         at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
>         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
>         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
>         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
>         at xsbt.boot.Using$.withResource(Using.scala:10)
>         at xsbt.boot.Using$.apply(Using.scala:9)
>         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
>         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
>         at xsbt.boot.Locks$.apply0(Locks.scala:31)
>         at xsbt.boot.Locks$.apply(Locks.scala:28)
>         at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
>         at sbt.IvySbt.withIvy(Ivy.scala:123)
>         at sbt.IvySbt.withIvy(Ivy.scala:120)
>         at sbt.IvySbt$Module.withModule(Ivy.scala:151)
>         at sbt.IvyActions$.updateEither(IvyActions.scala:157)
>         at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
>         at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
>         at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
>         at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
>         at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
>         at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
>         at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
>         at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
>         at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
>         at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
>         at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
>         at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
>         at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
>         at sbt.std.Transform$$anon$4.work(System.scala:63)
>         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
>         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
>         at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
>         at sbt.Execute.work(Execute.scala:235)
>         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
>         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
>         at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
>         at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> [error](*:update) sbt.ResolveException: unresolved dependency: com.hanhuy.sbt#android-gradle-build;1.1.9-SNAPSHOT: not found

**Comment by pfn** [comment]
Change to a non snapshot version

##
