### ISSUE TITLE
Not a valid  key:protify

### ISSUE THREAD

**Issue by mtretowicz** [pfn/protify#14]
After creating empty project in android studio and following all instructions in readme this is what i can and cannot do:
- app/android:run works just fine
- typing ~app/protify results in:
  [error] Expected ':' (if selecting a configuration)
  [error] Not a valid key: protify (similar: project-info, projectInfo, project-id
  )
  [error] app/protify
  [error]            ^
- Waiting for source changes... (press enter to interrupt)
  After saving some simple changes i layout file (like changing background) there is a change in console but nothing actuallu happens on the device:
  [error] Expected ':' (if selecting a configuration)
  [error] Not a valid key: protify (similar: project-info, projectInfo, project-id
  )
  [error] app/protify
  [error]            ^
- Waiting for source changes... (press enter to interrupt)

**Comment by pfn** [comment]
Put `protifySettings` in app/build.sbt

**Comment by mtretowicz** [comment]
Thanks.
my build.sbt looks like this:
android.Plugin.withVariant("app", None, None)

protifySettings

and after typing ~app/protify and saving some changes i get success message but nothing changes on the device (kitkat), on emulator i get the following message

04:34:14 E/ddms: transfer error: Read-only file system
04:34:14 E/Device: Error during Sync: Read-only file system
[trace] Stack trace suppressed: run last app/*:protify for the full output.
[error](app/*:protify) com.android.ddmlib.SyncException: Read-only file system
[error] Total time: 1 s, completed 2016-05-13 16:34:14

**Comment by pfn** [comment]
You must configure an SD card for the emulator

**Comment by pfn** [comment]
If you see no changes, describe the change and provide the build log

**Comment by mtretowicz** [comment]
Everything works fine now, thanks.
