### ISSUE TITLE
Error during Sync: timeout

### ISSUE THREAD

**Issue by neshkeev** [pfn/protify#18]
I tried to install a simple HelloWorld app which was generated by `gen-android` to 2 devices (not emulator) and I got the following error:

```
> set allDevices in Android := true
.....
> android:run
.....
[info] Installing to MySmartPhoneNameIsHere (0123456789ABCDEF)...
22:57:37 E/Device: Error during Sync: timeout.
[error] Install failed: null
[error] (android:install) Install failed: null
[error] Total time: 21 s, completed Aug 29, 2016 22:57:37 AM
```

Please suggest how to work it through.

**Comment by pfn** [comment]
Sounds like adb doesn't like your devices. adb kill-server and try again

**Comment by neshkeev** [comment]
The problem occurs only when I add this plugin to the project. When I remove the plugin from the project/plugins.sbt file, the app starts well on both my devices. I have tried adb kill-server, nothing happened, the problem persists. BTW, `export ADB_INSTALL_TIMEOUT=20` didn't work either.

**Comment by pfn** [comment]
protify does nothing to affect the install process. It's possible with protify that your apk size increased dramatically and because of this, the install failed, however.

**Comment by neshkeev** [comment]
I successfully installed the apk manually:

```
$ adb install target/android/output/tmp-debug-unaligned.apk 
261 KB/s (3871651 bytes in 14.443s)
    pkg: /data/local/tmp/tmp-debug-unaligned.apk
Success
```

but I failed to install it with sbt:

```
> set allDevices in Android := true
[info] Defining android:allDevices
[info] The new value will be used by *:protify, *:protifyLayout and 10 others.
[info]  Run `last` for details.
[info] Reapplying settings...
[info] Set current project to tmp (in build file:/home/a/projects/temp/temp/tmp/)
> [warn] UPDATE: A newer sbt-android is available: 1.6.15, currently running: 1.6.14
[warn] UPDATE: A newer sbt-android-protify is available: 1.3.2, currently running: 1.3.1
> android:run
[warn] androidTest: test-only aar will not have resources merged com.android.support.test:runner:0.5:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test:exposed-instrumentation-api-publish:0.5:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test.espresso:espresso-core:2.2.2:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test:rules:0.5:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test.espresso:espresso-idling-resource:2.2.2:androidTest
[info] Packaged: tmp-debug-unaligned.apk (3.69MB)
[info] Debug package does not need signing: tmp-debug-unaligned.apk
[info] zipaligned: tmp-debug.apk
[info] Installing to MySmartphoneNameIsHere (0123456789ABCDEF)...
09:12:16 E/Device: Error during Sync: timeout.
[error] Install failed: null
[error] (android:install) Install failed: null
[error] Total time: 19 s, completed Aug 31, 2016 09:12:16 PM
```

BWT: I use:
- Arch Linux
- <pre>$ sbt sbtVersion
  [info] Loading global plugins from /home/a/.sbt/0.13/plugins
  [info] Loading project definition from /home/a/projects/temp/temp/tmp/project
  [info] Set current project to tmp (in build file:/home/a/projects/temp/temp/tmp/)
  [info] 0.13.12</pre>

I can upload the project to my GitHub, if you wish.

**Comment by pfn** [comment]
Update as indicated.

**Comment by neshkeev** [comment]
Now another error occurs:

<pre>
> android:run
[warn] androidTest: test-only aar will not have resources merged com.android.support.test:runner:0.5:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test:exposed-instrumentation-api-publish:0.5:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test.espresso:espresso-core:2.2.2:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test:rules:0.5:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test.espresso:espresso-idling-resource:2.2.2:androidTest
[info] Packaged: tmp-debug-unaligned.apk (3.69MB)
[info] Debug package does not need signing: tmp-debug-unaligned.apk
[info] zipaligned: tmp-debug.apk
[info] Installing to MySmartphoneNameIsHere (0123456789ABCDEF)...
<b>[error] Install failed: Failed to establish session</b>
[error] (android:install) Install failed: Failed to establish session
[error] Total time: 14 s, completed Aug 31, 2016 10:29:01 AM
</pre>

I have tried to run the app on 3 different devices (not emulator), each yelds the same error.

**Comment by pfn** [comment]
Oops, look like I might have broken `sbt-android` by adding this "fix" -- installing packages with a timeout requires v21+ -- if your device is older than lollipop, you will probably get this error.

What device are you trying this on.

**Comment by neshkeev** [comment]
That is right, all of my devices are older than lollipop
I guess I will work without this plugin, thanks anyway.

**Comment by pfn** [comment]
For now you can downgrade to 1.6.14 and 1.3.1 and set the following in build.sbt

`initialize ~= { _ => android.ddmlib.DdmPreferences.setTimeOut(30000) }`

**Comment by neshkeev** [comment]
Now I gets uploaded just fine, but it doesn't start, it hangs for a while and then just crushes with the "Unfortunately, hwapp has stopped" message. I have checked it on two devices.

**Comment by pfn** [comment]
What is the exception, paste the output of `pidcat`

**Comment by neshkeev** [comment]
Hi, pidcat doesn't work on my computer yet, here is the logcat stacktrace:

```
FATAL EXCEPTION: main
Process: com.mycorp, PID: 4591
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
    at com.hanhuy.android.protify.agent.ProtifyApplication.attachBaseContext(ProtifyApplication.java:172)
    at android.app.Application.attach(Application.java:181)
    at android.app.Instrumentation.newApplication(Instrumentation.java:991)
    at android.app.Instrumentation.newApplication(Instrumentation.java:975)
    at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4514)
    at android.app.ActivityThread.access$1500(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5299)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
    at dalvik.system.NativeStart.main(Native Method)
Force finishing activity com.mycorp/.MainActivity
```

**Comment by pfn** [comment]
Why try so hard to hide the device you are running on?

**Comment by pfn** [comment]
And for that matter, `sbt-android` includes `pidcat`: `$ sbt pidcat`

**Comment by pfn** [comment]
BTW, use pidcat, report back.
