### ISSUE TITLE
Found interface but class was expected

### ISSUE THREAD

**Issue by maciek252** [pfn/protify#19]
I get the following error when trying to run sbt. Sbt version 0.13.12, the latest java 8.

[error] java.lang.IncompatibleClassChangeError: Found interface scalaz.Memo, but class was expected

What is the cause? I can find that such errors usually mean that a part of the code has been compiled with another version of gradle? java?

I try to add protify to a running and compilable android app.

**Comment by pfn** [comment]
Everything needs to be on latest versions because of the scalaz bincompat
update

**Comment by maciek252** [comment]
After removing .ivy2 and .sbt directories from my home directory, and doing several attempts everything compiles at last, thanks!

**Comment by pfn** [comment]
That's a bit overkill. Probably had an older version of sbt-android in
Global
