### ISSUE TITLE
java.lang.Class cannot be cast to android.app.ContextImpl$ServiceFetcher

### ISSUE THREAD

**Issue by seroperson** [pfn/protify#2]
Hello. I tired to start it with android:run on android-19 device and it fails at startup. If you need any more information just tell me. 

``` java
D/AndroidRuntime(20654): Shutting down VM
E/AndroidRuntime(20654): FATAL EXCEPTION: main
E/AndroidRuntime(20654): Process: com.example.debug, PID: 20654
E/AndroidRuntime(20654): java.lang.RuntimeException: Unable to create application com.example.debug.DebugApplication: java.lang.ClassCastException: java.lang.Class cannot be cast to android.app.ContextImpl$ServiceFetcher
E/AndroidRuntime(20654):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4640)
E/AndroidRuntime(20654):        at android.app.ActivityThread.access$1500(ActivityThread.java:155)
E/AndroidRuntime(20654):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
E/AndroidRuntime(20654):        at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(20654):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(20654):        at android.app.ActivityThread.main(ActivityThread.java:5388)
E/AndroidRuntime(20654):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(20654):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(20654):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
E/AndroidRuntime(20654):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
E/AndroidRuntime(20654):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(20654): Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to android.app.ContextImpl$ServiceFetcher
E/AndroidRuntime(20654):        at android.app.ContextImpl.getSystemService(ContextImpl.java:1742)
E/AndroidRuntime(20654):        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:557)
E/AndroidRuntime(20654):        at com.hanhuy.android.protify.agent.internal.ProtifyLayoutInflater.install(ProtifyLayoutInflater.java:68)
E/AndroidRuntime(20654):        at com.hanhuy.android.protify.agent.Protify.install(Protify.java:27)
E/AndroidRuntime(20654):        at com.example.debug.DebugApplication.onCreate(DebugApplication.scala:10)
E/AndroidRuntime(20654):        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime(20654):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4637)
E/AndroidRuntime(20654):        ... 10 more
```

**Comment by pfn** [comment]
What version are you using? Current is 0.8

##

**Comment by seroperson** [comment]
Yes, I use 0.8

**Comment by pfn** [comment]
Probably a bug I introduced when adding support for android-23. I'll fix it
next week.

##

**Comment by pfn** [comment]
You can back down to 0.6 for now and it should work.

**Comment by seroperson** [comment]
I think you forgot to upload it to maven. I can't resolve dependency already about a week =)
And [there](https://repo1.maven.org/maven2/com/hanhuy/android/protify-agent/) is no "0.9.1" directory

**Comment by pfn** [comment]
Quite possible, I hate sonatype, will publish on Monday

##

**Comment by mimoccc** [comment]
Solution (in activity or app)

   @Override
    public Intent registerReceiver(BroadcastReceiver receiver, IntentFilter filter) {
        try {
            return getRealBaseContext().registerReceiver(receiver, filter);
        } catch (Exception e) {
            e.printStackTrace();

            return null;
        }
    }

    @Override
    public Intent registerReceiver(BroadcastReceiver receiver, IntentFilter filter, String broadcastPermission, Handler scheduler) {
        try {
            return getRealBaseContext().registerReceiver(receiver, filter, broadcastPermission, scheduler);
        } catch (Exception e) {
            e.printStackTrace();

            return null;
        }
    }

    @RequiresApi(api = Build.VERSION_CODES.O)
    @Override
    public Intent registerReceiver(BroadcastReceiver receiver, IntentFilter filter, int flags) {
        try {
            return getRealBaseContext().registerReceiver(receiver, filter, flags);
        } catch (Exception e) {
            e.printStackTrace();

            return null;
        }
    }

    @RequiresApi(api = Build.VERSION_CODES.O)
    @Override
    public Intent registerReceiver(BroadcastReceiver receiver, IntentFilter filter, String broadcastPermission, Handler scheduler, int flags) {
        try {
            return getRealBaseContext().registerReceiver(receiver, filter, broadcastPermission, scheduler, flags);
        } catch (Exception e) {
            e.printStackTrace();

            return null;
        }
    }

    @Override
    public void unregisterReceiver(BroadcastReceiver receiver) {
        try {
            getRealBaseContext().unregisterReceiver(receiver);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Initialize custom libraries & code for debug
     */
    protected void initDebug() {
        if (BuildConfig.DEBUG) {
            try {
                Class<?> cls = Class.forName("no.telia.bedriftsnett.debug.Debug");

                Method m = cls.getMethod("init", Application.class);

                m.invoke(null, this);
            } catch (Exception e) {
            }
        }
    }

    protected Context getRealBaseContext() {
        Context c = getBaseContext();

        while ((c != null) && (c instanceof ContextWrapper)) {
            try {
                c = ((ContextWrapper) c).getBaseContext();
            } catch (Exception e) {
                e.printStackTrace();

                c = null;
            }
        }

        return c;
    }
