### ISSUE TITLE
Can it work with Dagger 2?

### ISSUE THREAD

**Issue by steffkelsey** [pfn/protify#9]
Hi, Love the plugin. I am trying to get it working with Android Studio and Dagger 2. I don't think the annotation processor is running. Does sbt work with the android-apt gradle plugin and if so how can I get it the dagger-compiler to run before everything else?

**Comment by pfn** [comment]
I haven't tried dagger 2, but dagger 1.2.1 works transparently.

If dagger 2 requires a separate build step, it would have to be implemented
manually in sbt

##

**Comment by steffkelsey** [comment]
Do you have a sample project with dagger 1? I might just be setting things up wrong. I have dagger 2 setup with the android-apt plugin and the dagger-compiler dependency is not showing up in the gradle-generated.sbt. I tried adding it in a build.sbt file. I'll see if I can post a sample this weekend

**Comment by pfn** [comment]
I was able to build the [android-simple](https://github.com/google/dagger/tree/master/examples/android-simple) example app using the following in build.sbt, you probably only need the last 3 `libraryDependencies` lines:

``` scala
androidBuild

platformTarget := "android-23"

libraryDependencies += "com.google.dagger" % "dagger" % "2.0.2"

libraryDependencies += "com.google.dagger" % "dagger-compiler" % "2.0.2" % "provided"

libraryDependencies += "javax.inject" % "javax.inject" % "1" % "provided"

libraryDependencies += "org.glassfish" % "javax.annotation" % "10.0-b28" % "provided"
```

I could not build the `android-activity-graphs` sample as I got errors in dagger2 generated source.

```
[error] dagger\examples\android-activity-graphs\bin\intermediates\classes\com\example\dagger\activitygraphs\ui\DaggerHomeComponent.java:44: method create in class com.example.dagger.activitygraphs.ui.HomeActivity_MembersInjector cannot be applied to given types;
[error]   required: javax.inject.Provider<android.location.LocationManager>
[error]   found: dagger.MembersInjector,javax.inject.Provider<android.location.LocationManager>
[error]   reason: actual and formal argument lists differ in length
[error] HomeActivity_MembersInjector.create
[error] dagger\examples\android-activity-graphs\bin\intermediates\classes\com\example\dagger\activitygraphs\ui\DaggerHomeComponent.java:46: method create in class com.example.dagger.activitygraphs.ui.HomeFragment_MembersInjector cannot be applied to given types;
[error]   required: javax.inject.Provider<com.example.dagger.activitygraphs.ui.ActivityTitleController>
[error]   found: dagger.MembersInjector,javax.inject.Provider<com.example.dagger.activitygraphs.ui.ActivityTitleController>
[error]   reason: actual and formal argument lists differ in length
[error] HomeFragment_MembersInjector.create
```

**Comment by charafau** [comment]
@steffkelsey after talk with @pfn I think I know why it didn't work for you. Where is your build.sbt file? Are you using `android-gradle-build` plugin? If yes, create `build.sbt` in `app/` folder (or whatever your application folder is), and specify dependency to dagger2 inside it, like:

``` scala
libraryDependencies += "com.google.dagger" % "dagger-compiler" % "2.0.2" % "provided"
```
